packages:
  # main next.js apps
  - 'apps/bvbrc'
  - 'apps/maage'
  - 'apps/dxkb'
  - 'apps/ldkb'
  # other next.js apps
  - 'apps/brc-docs'
  - 'apps/brc-storybook'
  - 'apps/brc-playground'
  # legacy node.js app
  - 'apps/bvbrc-legacy'
  # shared packages
  - 'packages/*'